### PR TITLE
Changes for integrating spvgen into amdvlk cmake build system

### PR DESCRIPTION
**Pull request by trenouf**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by JacobHeAMD** [comment]
ok to test

**Comment by JacobHeAMD** [comment]
test this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 342d6e6b7971704e8245ce3ae9a89fb27a47ebe2
<details open><summary>Driver commits used in build</summary><ul>

<li>LLPC: dev 6c6de1dab3927bfb0f6659ba89c6fe80be8a4a04</li>
<li>PAL: dev 99901922d67e502ff4233a8bfcbfa0347c0ffa1b</li>
<li>XGL: dev 5b4058dc288a25f6554fcc61f80bf3f27eb35d8d</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 342d6e6b7971704e8245ce3ae9a89fb27a47ebe2
<details open><summary>Driver commits used in build</summary><ul>

<li>LLPC: dev aaf71b57baa7d846ecf2e40a79cbb91bd0d1f2e3</li>
<li>PAL: dev 99901922d67e502ff4233a8bfcbfa0347c0ffa1b</li>
<li>XGL: dev 9795e006e9adb7b49b8abd32cd47c49b290fa3fc</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 901/901 (100.0%)</li>
<li>Failed: 0/901 (0.0%)</li>
</ul></details>

**Pull request merged**
