### PR TITLE
For test.

### PR DESCRIPTION
**Pull request by qiaojbao**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
Great stuff!

**Comment by qiaojbao** [comment]
Great stuff!
 Great stuff!
 Great stuff!

**Comment by qiaojbao** [comment]
Great stuff!
 Great stuff!
 Great stuff!

**Comment by qiaojbao** [comment]
Great stuff!
 Great stuff!

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
949874ac1aadba2e54fa4f8224b77831cf5736dd build error.
CMake Error at /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/spvgen-github-pr/driver_build/spvgen/CMakeLists.txt:30:
Parse error.  Expected a command name, got unquoted argument with text
"{}".

**Comment by qiaojbao** [comment]
949874ac1aadba2e54fa4f8224b77831cf5736dd build error.
CMake Error at /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/spvgen-github-pr/driver_build/spvgen/CMakeLists.txt:30:
Parse error.  Expected a command name, got unquoted argument with \ text
"{}".

**Comment by amdvlk-admin** [comment]
949874ac1aadba2e54fa4f8224b77831cf5736dd Jenkins build error.
CMake Error at /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/spvgen-github-pr/driver_build/spvgen/CMakeLists.txt:30:
  Parse error.  Expected a command name, got unquoted argument with text
   {} .

**Comment by amdvlk-admin** [comment]
949874ac1aadba2e54fa4f8224b77831cf5736dd Jenkins build error.
CMake Error at /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/spvgen-github-pr/driver_build/spvgen/CMakeLists.txt:30:
  Parse error.  Expected a command name, got unquoted argument with text
   {} .

**Pull request closed without merging**
